[project]
name = "PyFoundry"
version = "0.1.0"
description = "A modern Python project forge with pre-configured tooling and CI/CD."
authors = [{ name = "Sunil Ghimire", email = "info@sunilghimire.com.np" }]
readme = "README.rst"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.0",
]

[project.urls]
homepage = "https://github.com/ghimiresunil/PyFoundry.git"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.0",
]
