[default]
app_name = "MyTEST"

[default.database]
db_check = "check_db"

[dev]
dev_check = "check_db"
calibration_error = 5

[dev.database]
name = "app_dev_db"
host = "localhost"

[stage]
stage_check = "check_stage"

[stage.database]
name = "app_stage_db"
host = "stage.db.example.com"

[prod]
prod_check = "check_prod"
calibration_error = 1

[prod.database]
name = "app_prod_db"
host = "prod.db.example.com"
